dist: trusty
sudo: required
language: node_js
node_js:
  - "12"
addons:
  chrome: stable
cache:
  directories:
    - ./node_modules
before_script:
  - cp src/environments/environment.travis.ts src/environments/environment.ts
  - npm install -g @angular/cli
  - npm install
script:
  # - webdriver-manager update
  # - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
deploy:
  - provider: heroku
    app: frontend-linkedpet-prod-v2
    strategy: git
    api_key:
      secure: YcUGxwklQI6BCWNMdAULyB5ajqEhIaJprwI/jXFgJVPqaMMIcYmeLcN9fPcWiEW+N5GQ3+Q5FA5E+HHXzy65/YnrvvbRGlbi2aFUNmJtxXSqjb8TYlrUKsioPW5N6UY0EM2AqEaumR6UEk6esqv2zVp99l1mzAzMtMiundPIynmWksggkwxCMBf75F7RRGOyaXp+ie33Umlq+IiWKVNCKLyjcQ/79lxt8T6mJQPde1gbATk/U8qwftdXxjBTdJq/1Wp+6Q3Iw98U60xeesUuK5XpB33ifSGv/hStfcM1au0rr96tWxi+SJk9vrDV3Miu3Tu9rmGrGq9d1a/Lnwo1W8osT6VDGUMpqNnNXOETEthTlmgXYEbvR4d66piHJTHzSjo8jQM8UbSxhHv4US/u6QYoumyvO9a4y+SrKZrtS4X+yRshGrC6NIcHAoWcEmsnptE0fayiu9lpPgKUtRb5mIm8pWkTcsfh0d3nucL6IBqp5bSbykt+KitdzYCrlkoj9yciZe59G81YXtuVRlg87PFvsUViImlxsKpC7XVQRKksrDofazeI0r6di02A2JLlS5CWUvuQMQO5/qsQ40EdDSBPvlOZIFmYE2mEAHEOPS9UrA7Pl213Gnz4zsg0NAYlSRbovTrBcJA226bgQVIQnCdNG99TWNbaM/EYMpv1KUQ=
    on:
      branch: master
      tags: true
